### ISSUE TITLE
关于EDXP测试情况

### ISSUE THREAD

**Issue by wzgrx** [1595901624/mhyzzy#1]
EDXP最新版3.0测试了最新版的麻花助手.麻花是2.61版，激活模块后打开麻花，没有任何修改效果
作者可以来群里测试一下嘛，希望能够支持edxp，辛苦作者了
欢迎加入EdXpsoed卍TaiChi 交流群，群聊号码：984833480

**Comment by 1595901624** [comment]
好的

**Comment by wzgrx** [comment]
> 好的

大佬来了没有，id是多少（｡ò ∀ ó｡）

**Comment by 06ji** [comment]
> EDXP最新版3.0测试了最新版的麻花助手.麻花是2.61版，激活模块后打开麻花，没有任何修改效果
> 作者可以来群里测试一下嘛，希望能够支持edxp，辛苦作者了
> 欢迎加入EdXpsoed卍TaiChi 交流群，群聊号码：984833480

3.0本来是有问题，我们都倒退2.9.9bate2，正常使用，请不要适配3.0，3.0这个包BUG太多了，很多模块不生效

**Comment by 06ji** [comment]
> 好的

3.0本来是有问题，我们都倒退2.9.9bate2，正常使用，请不要适配3.0，3.0这个包BUG太多了，很多模块不生效

**Comment by 1595901624** [comment]
0.6.5 Beta 已经支持 Exposed 框架

**Comment by kettly1260** [comment]
测试了一下，vxp使用正常，除了每次登录后出现的那个弹窗，但是完全不影响使用

**Comment by afteragain** [comment]
> 测试了一下，vxp使用正常，除了每次登录后出现的那个弹窗，但是完全不影响使用

vxp里使用正常吗？我勾选了模块就报错退出了额（模块开关为关的状态）

**Comment by 1595901624** [comment]
> > 测试了一下，vxp使用正常，除了每次登录后出现的那个弹窗，但是完全不影响使用
> 
> vxp里使用正常吗？我勾选了模块就报错退出了额（模块开关为关的状态）

太极已经支持0.6.5，您可以试一下

**Comment by 1595901624** [comment]
> 测试了一下，vxp使用正常，除了每次登录后出现的那个弹窗，但是完全不影响使用

太极已经支持0.6.5，您可以试一下

**Comment by afteragain** [comment]
> > 测试了一下，vxp使用正常，除了每次登录后出现的那个弹窗，但是完全不影响使用
> 
> 太极已经支持0.6.5，您可以试一下

能把投屏需要麻花币限制的那个给弄掉吗？谢谢
还有麻花的后花园风驰影视是不是也要支持下？

**Comment by 1595901624** [comment]
> > > 测试了一下，vxp使用正常，除了每次登录后出现的那个弹窗，但是完全不影响使用
> > 
> > 
> > 太极已经支持0.6.5，您可以试一下
> 
> 能把投屏需要麻花币限制的那个给弄掉吗？谢谢
> 还有麻花的后花园风驰影视是不是也要支持下？

风驰和投屏已经在考虑了，谢谢提议
